# Generated by Django 6.0 on 2026-10-01 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('expected_outcome', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open for Proposals', 'Open for Proposals'), ('Evaluating', 'Evaluating'), ('Pilot Phase', 'Pilot Phase'), ('Closed', 'Closed')], default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain_focus', models.CharField(max_length=255)),
                ('is_dpiit_verified', models.BooleanField(default=False)),
                ('pilots_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
