# Generated by Django 6.0 on 2026-10-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('solution_details', models.TextField()),
                ('milestones', models.JSONField(help_text="Format: [{'name': 'M1', 'amount': 50000}]")),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved for Pilot', 'Approved for Pilot'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.challenge')),
            ],
        ),
    ]
