# Generated by Django 6.0 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailotp_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
